### ISSUE TITLE
After Installation

### ISSUE THREAD

**Issue by bornhaeusser** [goosehub/landgrab#4]
Did run the installation on my host and got:

`404 Page Not Found

We're sorry, but we couldn't find the page you were looking for, or an unknown error occured.

Please consider telling me about what happened.
goosepostbox@gmail.com`

**Comment by bornhaeusser** [comment]
fail....

**Comment by goosehub** [comment]
You closed this issue? Did you figure it out?

If not, it's most likely that you might not have the worlds in your database. Have you imported the sql files in sql/worlds into your database?

An easy way to check if this is related to the problem, comment out this if statement here.

https://github.com/goosehub/landgrab/blob/master/application/controllers/Game.php#L57

If you get different behavior than 404, then the model is unable to get the worlds from the database, most likely because they aren't there.

Hope this helps!

**Comment by bornhaeusser** [comment]
Thanks for your comment. Did forget to put the tiny.sql in the db :-)
