### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stats' of undefined

### ISSUE THREAD

**Issue by ROMTypo** [goosehub/landgrab#5]
![screen shot 2018-08-23 at 9 36 50 pm](https://user-images.githubusercontent.com/18755147/44563722-aee58380-a71c-11e8-994f-ac0242ae0a15.png)

Happens on local installation, when I click on a tile on the map, file following the latest install instructions.

**Comment by goosehub** [comment]
Hey, thanks for your interest.

I spun up a fresh install of landgrab using a new web folder, new database, etc. I was not able to replicate. However, looking at the code, I have some ideas.

.stats as a property is only called inside of the file `map_script.php` inside of function `update_leaderboards()`. All this function does is update the leaderboard, so if this is the problem and you don't require the leaderboard, you can just comment out the function call `update_leaderboards(data);` around line 933.

Reasons this could be failing is a bad response when requesting the leaderboard from the server. Leaderboards are held in JSON instead of DB as a form of caching to reduce DB and improve performance load under heavy use). Because of this, it's very important that the web server can read and write to the json folder. If you want to use the leaderboard and this is the problem, set file permissions correctly (or loosely) for that folder, and create `leaderboard_1.json`, `leaderboard_2.json` if the server is for some reason not creating the files. Good file permissions for that folder should solve the issue, if that's the issue.

You said it was happening on tile click though, which suggests it's something else. When you click the link in the error to view the code, what is the code where it's trying to access property stats?

That question might be enough to answer it, but if you want to be through, a few other questions. Does it happen when logged in, logged out, or both? Does it happen on claimed land, unclaimed land, or both? Do the window pop up when clicking on a tile?

Hope this helps! I'd love to make sure users are able to spin up their own instances of Landgrab, so I hope you can get back to me so we can get this working. Thanks!

**Comment by goosehub** [comment]
Closing as no follow up
